import { GoogleGenerativeAI } from "@google/generative-ai";
import type {
  CampaignBrief,
  ProductImage,
  Script,
} from "../types";
import { getPersona } from "./personas";
import { normalizeScenes, stripJson, type RawScene } from "./scriptUtils";

// Free-tier note: as of mid-2026 some accounts have zero free-tier quota for
// gemini-2.0-flash. gemini-2.5-flash typically has its own separate quota
// allocation, so default to that.
const MODEL = "gemini-2.5-flash";

function buildPrompt(brief: CampaignBrief) {
  const persona = getPersona(brief.personaId);
  const targetWords = Math.round(brief.duration * 2.4);
  const sceneCountInstr = "4-6 scenes total.";
  const engineNote = `\nThe footage will be generated by fal.ai's image-to-video model (Kling) using the uploaded product photo as the first frame. Make scene "description" and "acting" cinematic, specific, and visually grounded — they feed directly into the video prompt.`;

  return `You are an elite UGC ad scriptwriter for short-form video.
Write an organic, scroll-stopping ad for ${brief.platform}.

Brief:
- Target audience: ${brief.audience || "general consumers"}
- Tone: ${brief.tone}
- Duration: ${brief.duration} seconds (~${targetWords} spoken words total)
- Marketing angle: ${brief.angle || "highlight the strongest benefit"}
- Special instructions: ${brief.notes || "none"}
${
  brief.productDescription
    ? `- Product description from creator: ${brief.productDescription}`
    : ""
}${
    brief.researchNotes ? `\n\n${brief.researchNotes}` : ""
  }${engineNote}

AI creator persona — match this voice exactly when writing every voice line:
- ${persona.name}
- ${persona.styleNotes}

Use the attached product images as visual references. The creator is filming an authentic UGC review with the product in hand.

Return STRICT JSON ONLY (no prose, no markdown fences) matching this schema:
{
  "hooks": [string, string, string, string, string],
  "scenes": [
    {
      "voiceLine": string,
      "description": string,
      "acting": string,
      "bRoll": string,
      "duration": number
    }
  ],
  "cta": string
}

Rules:
- 5 hooks, each under 15 words. Hook #1 should be the strongest scroll-stopper.
- ${sceneCountInstr} The concatenation of all "voiceLine" fields IS the spoken script.
- Total spoken words across all scenes ≈ ${targetWords}.
- Scene durations are integers in seconds and must sum to exactly ${brief.duration}.
- "voiceLine" is what the creator says in that scene only. Keep it natural, no scene labels, no stage directions.
- "description" is what the camera shows (subject, framing, environment, lighting).
- "acting" describes facial expression, body language, energy, eye contact.
- "bRoll" is one optional cutaway suggestion (product close-up, lifestyle, hand-held demo).
- "cta" is one direct, punchy call to action — separate from the scenes.`;
}

function dataUrlToInlinePart(image: ProductImage) {
  const base64 = image.dataUrl.split(",")[1] ?? "";
  return {
    inlineData: {
      data: base64,
      mimeType: image.mimeType,
    },
  };
}

/**
 * Translate raw Google SDK errors into actionable user-facing messages.
 */
function friendlyError(e: unknown, context: string): Error {
  const raw = e instanceof Error ? e.message : String(e);

  if (/\b429\b/.test(raw) || /quota/i.test(raw) || /rate limit/i.test(raw)) {
    const limitZero = /limit:\s*0\b/i.test(raw);
    const isFreeTier = /free_tier/i.test(raw);
    if (limitZero && isFreeTier) {
      return new Error(
        `Gemini ${context} blocked: this Google project has 0 free-tier quota for "${MODEL}". Fixes: (1) enable billing at console.cloud.google.com → APIs & Services → Generative Language API, or (2) use an API key from a different project that still has free tier.`,
      );
    }
    return new Error(
      `Gemini ${context} hit a rate limit. Wait ~30s and retry, or enable billing for higher limits.`,
    );
  }

  if (/\b401\b|\b403\b|API_KEY_INVALID|PERMISSION_DENIED/i.test(raw)) {
    return new Error(
      `Gemini ${context} rejected the API key. Check the key in Settings, and that the Generative Language API is enabled on its Google project.`,
    );
  }

  if (/\b404\b|model.*not.*found|not.*supported/i.test(raw)) {
    return new Error(
      `Gemini ${context}: model "${MODEL}" is not available for this key. Try a different key or model.`,
    );
  }

  return new Error(`Gemini ${context} failed: ${raw.slice(0, 280)}`);
}

export async function generateScript(opts: {
  apiKey: string;
  brief: CampaignBrief;
  images: ProductImage[];
}): Promise<Script> {
  if (!opts.apiKey) throw new Error("Missing Gemini API key");
  if (opts.images.length === 0) throw new Error("Add at least one product image");

  const genAI = new GoogleGenerativeAI(opts.apiKey);
  const model = genAI.getGenerativeModel({
    model: MODEL,
    generationConfig: {
      temperature: 0.9,
      responseMimeType: "application/json",
    },
  });

  const parts = [
    { text: buildPrompt(opts.brief) },
    ...opts.images.map(dataUrlToInlinePart),
  ];

  let text: string;
  try {
    const result = await model.generateContent({
      contents: [{ role: "user", parts }],
    });
    text = result.response.text();
  } catch (e) {
    throw friendlyError(e, "script generation");
  }

  let parsed: {
    hooks?: string[];
    scenes?: RawScene[];
    cta?: string;
  };
  try {
    parsed = JSON.parse(stripJson(text));
  } catch {
    throw new Error("Gemini returned an invalid response. Try again.");
  }

  const scenes = normalizeScenes(parsed.scenes ?? [], opts.brief.duration);

  return {
    hooks: (parsed.hooks ?? []).slice(0, 5),
    selectedHookIndex: 0,
    scenes,
    cta: parsed.cta ?? "",
  };
}

export type RegenSection = "hooks" | "scenes" | "cta" | "scene";

export async function regenerateSection(opts: {
  apiKey: string;
  section: RegenSection;
  brief: CampaignBrief;
  current: Script;
  images: ProductImage[];
  sceneIndex?: number;
}): Promise<Partial<Script>> {
  const persona = getPersona(opts.brief.personaId);
  const genAI = new GoogleGenerativeAI(opts.apiKey);
  const model = genAI.getGenerativeModel({
    model: MODEL,
    generationConfig: {
      temperature: 1.0,
      responseMimeType: "application/json",
    },
  });

  const sectionInstr =
    opts.section === "hooks"
      ? `Rewrite ONLY the hooks. Return {"hooks": [5 strings]}.`
      : opts.section === "scenes"
      ? `Rewrite ONLY the scenes (${
          opts.brief.duration <= 8 ? "1-2" : "4-6"
        } scenes; voiceLine + description + acting + bRoll + duration; durations sum to ${opts.brief.duration}). Return {"scenes": [{voiceLine, description, acting, bRoll, duration}]}.`
      : opts.section === "cta"
      ? `Rewrite ONLY the CTA. Return {"cta": string}.`
      : `Rewrite ONLY scene index ${opts.sceneIndex} keeping the same duration. Return {"scenes": <full array with that one scene replaced>}.`;

  const prompt = `You are refining a UGC ad script for ${opts.brief.platform}.
Brief: ${JSON.stringify(opts.brief)}
Persona voice to match: ${persona.name} — ${persona.styleNotes}
Current script: ${JSON.stringify({
    hooks: opts.current.hooks,
    scenes: opts.current.scenes.map((s) => ({
      voiceLine: s.voiceLine,
      description: s.description,
      acting: s.acting,
      bRoll: s.bRoll,
      duration: s.duration,
    })),
    cta: opts.current.cta,
  })}

${sectionInstr}
Return STRICT JSON only.`;

  const parts = [
    { text: prompt },
    ...opts.images.slice(0, 4).map(dataUrlToInlinePart),
  ];

  let text: string;
  try {
    const result = await model.generateContent({
      contents: [{ role: "user", parts }],
    });
    text = result.response.text();
  } catch (e) {
    throw friendlyError(e, "regeneration");
  }
  const parsed = JSON.parse(stripJson(text)) as {
    hooks?: string[];
    cta?: string;
    scenes?: RawScene[];
  };

  const out: Partial<Script> = {};
  if (parsed.hooks) out.hooks = parsed.hooks.slice(0, 5);
  if (parsed.cta) out.cta = parsed.cta;
  if (parsed.scenes)
    out.scenes = normalizeScenes(parsed.scenes, opts.brief.duration);
  return out;
}
